### ISSUE TITLE
Error when calling the PRELES function without parameters 

### ISSUE THREAD

**Issue by florianhartig** [MikkoPeltoniemi/Rpreles#4]
Hi Mikko,

I was trying the new version from GitHub as well as the older model version that we had for a course that I'm running at the moment. In the old version, the following code creates no problem (s1 is a dataset with the drivers)

library(Rpreles)
attach(s1)

PRELES(PAR, TAir, VPD, Precip, CO2, fAPAR)

but the current GitHub version results in the following

/# error in console:
NAs in foreign function call (arg 57) 

I didn't check it out but one of the students suggested that the issue disappears when we call PRELES with a full set of parameters. But it should be possible to call it without as well, shouldn't it? At least the function interface suggests so.

**Comment by MikkoPeltoniemi** [comment]
Hi Florian, I didn't see your post, sorry. Apparently it was missing doy that caused problems. For conifers it is not needed, and one should vary fAPAR given as input if one wants to describe shoot phenology effects on GPP. Conifer phenology is not in the model....error stemmed from experiments with deciduous phenology.
